const supporterList = [
  {
    id: "FEB",
    logo: "logo-feb.png",
    title: "FEB",
    detail: {
      // article: `Sastro Conthong merupakan wadah untuk mendukung pejuang-pejuang ilmu budaya yang sedang berlaga di medan laga Porsenigama. sastro Conthong berisikan seluruh mahasiswa Ilmu Budaya tanpa terkecuali. Asal-usul nama Sastro Conthong berasal dari kata Sastro yang berarti sastra dan conthong berarti Mulut, sehingga Sastro Conthong bermakna Pendukung kontingen ilmu budaya yang siap bernyanyi bersorak untuk mendukung secara penuh kontingen Ilmu Budaya yang sedang berlaga di lapangan. Sastro Conthong mempunyai Slogan " Superbia in Cultura" yang berarti "Kebanggaan dalam budaya" serta mempunyai logo (maskot) kebanggan "Gajah Ganesha" Gajah Ganesha sendiri merupakan simbol kebijaksanaan, kebenaran dan keberanian dalam kehidupan.`,
      // article: "",
      video: "https://youtube.com/embed/ldMuRofHVsU",
      chant: "https://youtube.com/embed/ldMuRofHVsU",
      infografis: "peternakan.jpg",
    },
  },
  {
    id: "Biologi",
    logo: "logo-biologi.png",
    title: "Biologi",
    detail: {
      article: "",
      video: "",
      chant: "",
      infografis: "",
    },
  },
  {
    id: "Teknologi-Pertanian",
    logo: "logo-ftp.png",
    title: "Teknologi Pertanian",
    detail: {
      article: "",
      video: "",
      chant: "",
      infografis: "",
    },
  },
  {
    id: "FISIPOL",
    logo: "logo-isipol.png",
    title: "FISIPOL",
    detail: {
      article: "",
      video: "",
      chant: "",
      infografis: "",
    },
  },
  {
    id: "FIB",
    logo: "logo-fib.png",
    title: "FIB",
    detail: {
      article: "",
      video: "",
      chant: "",
      infografis: "",
    },
  },
  {
    id: "Fakultas-Hukum",
    logo: "logo-hukum.png",
    title: "Hukum",
    detail: {
      article: "",
      video: "",
      chant: "",
      infografis: "",
    },
  },
  {
    id: "Fakultas-Geografi",
    logo: "logo-geografi.png",
    title: "Geografi",
    detail: {
      article: "",
      video: "",
      chant: "",
      infografis: "",
    },
  },
  {
    id: "Fakultas-Filsafat",
    logo: "logo-filsafat.png",
    title: "Filsafat",
    detail: {
      article: "",
      video: "",
      chant: "",
      infografis: "",
    },
  },
  {
    id: "Fakultas-Farmasi",
    logo: "logo-farmasi.png",
    title: "Farmasi",
    detail: {
      article: "",
      video: "",
      chant: "",
      infografis: "",
    },
  },
  {
    id: "FKG",
    logo: "logo-fkg.png",
    title: "FKG",
    detail: {
      article: "",
      video: "",
      chant: "",
      infografis: "",
    },
  },
  {
    id: "FKH",
    logo: "logo-fkh.png",
    title: "FKH",
    detail: {
      article: "",
      video: "",
      chant: "",
      infografis: "",
    },
  },
  {
    id: "Teknik",
    logo: "logo-teknik.png",
    title: "Teknik",
    detail: {
      article: "",
      video: "",
      chant: "",
      infografis: "",
    },
  },
  {
    id: "SV",
    logo: "logo-vokasi.png",
    title: "SV",
    detail: {
      article: "",
      video: "",
      chant: "",
      infografis: "",
    },
  },
  {
    id: "Pascasarjana",
    logo: "logo-pascasarjana.png",
    title: "Pascasarjana",
    detail: {
      article: "",
      video: "",
      chant: "",
      infografis: "",
    },
  },
  {
    id: "Psikologi",
    logo: "logo-psikologi.png",
    title: "Psikologi",
    detail: {
      article: "",
      video: "",
      chant: "",
      infografis: "",
    },
  },
  {
    id: "Fakultas-Peternakan",
    logo: "logo-peternakan.png",
    title: "Peternakan",
    detail: {
      article: "",
      video: "",
      chant: "",
      infografis: "",
    },
  },
  {
    id: "Fakultas-Pertanian",
    logo: "logo-pertanian.png",
    title: "Pertanian",
    detail: {
      article: "",
      video: "",
      chant: "",
      infografis: "",
    },
  },
  {
    id: "MIPA",
    logo: "logo-mipa.png",
    title: "MIPA",
    detail: {
      article: "",
      video: "",
      chant: "",
      infografis: "",
    },
  },
  {
    id: "Fakultas-Kehutanan",
    logo: "logo-kehutanan.png",
    title: "Kehutanan",
    detail: {
      article: "",
      video: "",
      chant: "",
      infografis: "",
    },
  },
  {
    id: "FKKMK",
    logo: "logo-kkmk.png",
    title: "FKKMK",
    detail: {
      article: "",
      video: "",
      chant: "",
      infografis: "",
    },
  },
];
export { supporterList };
