export * from "./Home.jsx";
export * from "./Standings.jsx";
export * from "./Faq.jsx";
export * from "./Cabang.jsx";
export * from "./CabangDetail.jsx";
export * from "./Galeri.jsx";
export * from "./Katalog.jsx";
export * from "./KatalogDetail.jsx";
export * from "./404.jsx";
